### ISSUE TITLE
Arm64 support

### ISSUE THREAD

**Issue by tmdues** [wit-ai/wit-android-sdk#15]
I'm getting a force close whenever I try to toggle listening on wit.ai. The logcat output says it couldn't find libwitvad.so in the arm64 folder. Are you guys planning on supporting arm64 based architecture in the future?

08-26 14:28:25.626  10281-10281/[app name] E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: [app name], PID: 10281
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/[app name]-1/base.apk"],nativeLibraryDirectories=[/data/app/[app name]-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libwitvad.so"
            at java.lang.Runtime.loadLibrary(Runtime.java:366)
            at java.lang.System.loadLibrary(System.java:988)
            at ai.wit.sdk.WitMic.<clinit>(WitMic.java:46)
            at ai.wit.sdk.Wit.startListening(Wit.java:63)
            at ai.wit.sdk.Wit.toggleListening(Wit.java:94)
            at com.ui.voiceSearch.Fragment_Voice_Search.onCreateView(Fragment_Voice_Search.java:78)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1789)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:955)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:551)
            at com.ui.voiceSearch.Activity_Voice_Search.onStart(Activity_Voice_Search.java:135)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1304)
            at android.app.Activity.performStart(Activity.java:6034)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2380)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2480)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1377)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:155)
            at android.app.ActivityThread.main(ActivityThread.java:5725)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1030)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:825)

**Comment by carloskekwa** [comment]
is the prob solved?

**Comment by masmil1988** [comment]
Any news?

**Comment by prashantrane123** [comment]
No, not yet.

**Comment by vyguera** [comment]
You can compile libwitvad for any 64bit architecture with latest ndk
Anyway I'll attach my last compilation which also fixes a nullpointerexception when trying to stop listening without having stated it before.
[wit-android-sdk.zip](https://github.com/wit-ai/wit-android-sdk/files/294349/wit-android-sdk.zip)
